### PR TITLE
Pagination support

### PR DESCRIPTION
**Pull request by leprasmurf**
A bit of Beautification, a bit of commenting, some debugging, and pagination support (WIP) to all full import from netbox.

### CODE REVIEW

**Comment by leprasmurf** [comment]
Sorry, wrong target master.

**Comment by luto** [comment]
thank you very much!

since this one is closed now.. will you open another PR? :)

**Comment by luto** [comment]
feel free to delete any code that is commented out!

**Comment by luto** [comment]
@leprasmurf we'd love to have this :) are you planning on submitting a new PR with the correct target branch?

**Pull request closed without merging**
