### PR TITLE
Make the module compatible to Netbox 2.9.x

### PR DESCRIPTION
**Pull request by cannotcodetm**
Fix various things related to latest netbox changes, rename various things to improve code

### CODE REVIEW

**Comment by cannotcodetm** [comment]
#13 

@luto  @bb-Ricardo Please verify this pull request, it does work with my 2.9.3 installation properly now

@luto If successful please merge it to master :-)

**Comment by joni1993** [comment]
Thanks for the PR - it works with my Netbox 2.9.4!

**Comment by luto** [comment]
thank you!

**Comment by luto** [comment]
@m4k5ym which netbox version is the new minimum now?

**Comment by bb-Ricardo** [comment]
The minimum version with this commit would be 2.9

I personally keep running into timeouts. 

I would need a filter for objects with certain roles or tags to reduce the amount of objects returned for a request.

**Comment by cannotcodetm** [comment]
Would you open a new issue for your wish, please?

I'll have a look into it, also this issue can be considered as closed since it seem to work fine for now.

We all will come together again when netbox is producing its next major api desaster release for sure.

See ya

**Comment by bb-Ricardo** [comment]
Thank you so much for your work.

will open another issue.

**Pull request merged**
