### PR TITLE
Service imports & other improvements

### PR DESCRIPTION
**Pull request by joni1993**
* Services for Objects are now also imported
* Ability to specificy which parameters to flatten (default `custom_fields`, `interfaces` for compatibility)
* Ability to specifiy which additional properties to resolve (default `cluster`)
* Ability to manually flatten nested objects by using modifiers (needs https://github.com/Icinga/icingaweb2-module-director/pull/1721 to be merged)
* Fixed interface / service import for virtual machines

### CODE REVIEW

**Comment by luto** [comment]
thank you! I am waiting for Icinga/icingaweb2-module-director#1721 :)

**Comment by luto** [comment]
@joni1993 I'd love to merge this. Do you have any news on when we might get the linked PR?

**Comment by joni1993** [comment]
In the last days it got approved by a few people, so we eventually get it merged soon. :blush:

**Comment by joni1993** [comment]
@luto https://github.com/Icinga/icingaweb2-module-director/pull/1721 is merged in master :)

**Comment by luto** [comment]
thanks!

**Pull request merged**
